##################################
# Makefile
# # Beckham Carver
# # COSC 3750, Spring 2024
# # Homework 11
# # Last Modified Date: May 11, 2023
# #
# # Makefile for HW11
# ##################################


CC=gcc
CFLAGS=-ggdb -Wall

# reference to clean
.PHONY: clean

mmult: mmult.c
	${CC} ${CFLAGS} mmult.c -o mmult

# remove
clean:
	-rm -f mmult
